// src/lib/data.ts

export const siteConfig = {
  name: "Shubham Rathod",
  role: "AI Engineer",
  tagline: "Bridging the gap between Complex Data and Intelligent Action.",
  email: "shubhamrathod1619@gmail.com",
  github: "https://github.com/Rathod-shubhamm",
  linkedin: "https://www.linkedin.com/in/shubham-rathod-821a01202",
  socials: [
    { name: "GitHub", href: "https://github.com/Rathod-shubhamm", platform: "github" },
    { name: "LinkedIn", href: "https://www.linkedin.com/in/shubham-rathod-821a01202", platform: "linkedin" },
    { name: "Email", href: "mailto:shubhamrathod1619@gmail.com", platform: "email" },
  ]
};

export const projects = [
  {
    id: "social-media-automation",
    title: "EcoSystem AI",
    category: "AI & Automation",
    description: "An intelligent multi-agent orchestration platform that automates the entire content lifecycle—from semantic trend analysis to cross-platform deployment.",
    metrics: ["10K+ automated cycles", "95% semantic relevance"],
    image: "/assets/images/social-media.png",
    tags: ["Next.js", "Python", "OpenAI", "n8n"],
    architecture: "Stateful Agentic Workflows",
    stack: "GPT-4 / Next.js / PostgreSQL",
    latency: "< 1.2s generation",
    github: "https://github.com/Rathod-shubhamm",
    live: "#",
    featured: true,
  },
  {
    id: "football-performance-ai",
    title: "PitchPulse AI",
    category: "Machine Learning",
    description: "Predictive analytics engine for elite football performance, utilizing deep spatial-temporal data to forecast player impact and match outcomes.",
    metrics: ["88% predictive accuracy", "Per-second telemetry"],
    image: "/assets/images/football-ai.png",
    tags: ["Python", "Scikit-Learn", "FastAPI"],
    architecture: "Temporal Convolutional Nets",
    stack: "XGBoost / FastAPI / Docker",
    latency: "< 45ms inference",
    github: "https://github.com/Rathod-shubhamm",
    live: "#",
    featured: true,
  },
  {
    id: "crypto-sentiment",
    title: "MarketBrain AI",
    category: "AI / Finance",
    description: "Real-time volatility forecasting platform leveraging high-frequency NLP to quantify market sentiment across decentralized exchanges.",
    metrics: ["1M+ tokens indexed", "Live Sentiment Stream"],
    image: "/assets/images/crypto-sentiment.png",
    tags: ["Node.js", "FinBERT", "FastAPI"],
    architecture: "Distributed NLP Pipeline",
    stack: "PyTorch / Redis / Node.js",
    latency: "Real-time WebSocket",
    github: "https://github.com/Rathod-shubhamm",
    live: "#",
    featured: false,
  },
  {
    id: "encrypted-file-sharing",
    title: "OmniSafe P2P",
    category: "Security",
    description: "Enterprise-grade decentralized file sharing protocol featuring end-to-end AES-256-GCM encryption and ephemeral metadata handling.",
    metrics: ["AES-256-GCM Secure", "Zero-Knowledge Architecture"],
    image: "/assets/images/encrypted-sharing.png",
    tags: ["React", "Express", "MongoDB", "WebCrypto"],
    architecture: "E2EE + Ephemeral Storage",
    stack: "TypeScript / Node.js / AWS",
    latency: "Instant P2P Handshake",
    github: "https://github.com/Rathod-shubhamm",
    live: "#",
    featured: false,
  },
  {
    id: "ai-course-generator",
    title: "Lumina AI",
    category: "AI & Education",
    description: "A generative educational platform that architecturally constructs comprehensive curricula and interactive modules using RAG-enhanced LLMs.",
    metrics: ["Auto-Curriculum Generation", "RAG-driven Accuracy"],
    image: "/assets/images/course-generator.png",
    tags: ["Next.js", "LangChain", "VectorDB"],
    architecture: "Recursive RAG + Tree-of-Thought",
    stack: "Claude-3 / Pinecone / Next.js",
    latency: "< 4s per module",
    github: "https://github.com/Rathod-shubhamm",
    live: "#",
    featured: true,
  },
];

export const skillClusters = [
  {
    title: "AI & Machine Learning",
    skills: ["Machine Learning", "RAG & AI Agents", "LangChain", "Vector Databases", "LLMs (GPT-4, Claude, Gemini)"],
    icon: "🧠",
  },
  {
    title: "Backend & Systems",
    skills: ["Python", "FastAPI", "Node.js", "PostgreSQL", "Docker", "n8n"],
    icon: "⚙️",
  },
  {
    title: "Frontend Engineering",
    skills: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Framer Motion"],
    icon: "⚛️",
  },
  {
    title: "Infrastructure & Cloud",
    skills: ["AWS", "GCP", "Vercel", "CI/CD", "Serverless"],
    icon: "☁️",
  },
];

export const experience = [
  {
    company: "Apexneural Pvt Ltd",
    role: "AI Context Engineer",
    period: "Aug 2025 – Present",
    description: "Building intelligent automation systems, LLM pipelines, and full-stack AI products. Working across multi-agent orchestration, computer vision, data engineering, and scalable ML infrastructure.",
    achievements: [
      "Built a multi-platform social media automation system using GPT-4 & Stable Diffusion — publishing 10,000+ posts/month across Instagram, Twitter & LinkedIn for 100+ accounts with 99.2% uptime",
      "Architected 12 reusable prompt templates with output validation, improving generation speed by 25% and cutting monthly API costs by $500",
      "Constructed a resilient Reddit data ingestion pipeline (Python, BeautifulSoup, lxml) with adaptive selectors and fallback handling — maintaining 92% retrieval success rate",
      "Delivered a document automation platform (Next.js + FastAPI + GPT-4 Vision + Google Workspace APIs) processing 500+ documents weekly with OAuth 2.0 authentication",
      "Optimized analytics across 2TB+ of scraped data using FastAPI, PostgreSQL, and Redis caching — reducing average query latency from 12s to 3s",
      "Designed fault-tolerant async pipelines with task queues and recovery mechanisms, ensuring 99.7% data integrity across concurrent scraping workflows",
      "Built real-time sports analytics system using PyTorch, YOLOv8 & OpenCV for multi-object tracking and action recognition at 30 FPS, sub-100ms latency",
      "Applied semantic segmentation for player ID and boundary detection, reaching 89% mAP on a custom dataset of 10,000+ annotated frames",
      "Containerized microservices with Docker, reducing environment setup from 4 hours to 15 minutes across a 12-member team",
      "Established CI/CD workflows via GitHub Actions, compressing release cycles from 3 days to 4 hours",
      "Implemented a multi-agent company automation system (5 functional agents + CEO agent) integrating Jira and Slack to convert voice inputs into structured, trackable tasks",
      "Engineered a hybrid column-level data lineage system for Snowflake and BigQuery using sqlglot with LLM-based fallback for complex queries — enabling accurate source-to-target mapping at scale",
    ],
  },
  {
    company: "BlinkCare",
    role: "Technical Advisor & Consultant",
    period: "Late 2025 – Present",
    description: "Served as an independent technical consultant for BlinkCare (blinkcare.co.in), a healthcare-focused startup. Advised on tech stack selection, system architecture, and business strategy to help lay the foundation for a scalable product.",
    achievements: [
      "Guided tech stack selection & architecture decisions",
      "Advised on product strategy and go-to-market approach",
      "Supported early-stage platform setup and infrastructure planning",
    ],
  },
  {
    company: "Vellore Institute of Technology",
    role: "Computer Science Graduate",
    period: "2021 – 2026",
    description: "Integrated MTech in Artificial Intelligence at VIT Bhopal. Focused on AI/ML research and software engineering principles.",
    achievements: ["Class representative", "Developed 5+ major AI/ML projects", "CGPA: 7.79"],
  },
];
